### ISSUE TITLE
Lab 1: Unresolved template for @template.userRow

### ISSUE THREAD

**Issue by Riggs333** [tschuehly/htmx-spring-workshop#2]
Following the instructions in Lab 1, I got stuck for a moment with this error in IntelliJ, saying "Unresolved template" for `@template.userRow`:

![image](https://github.com/tschuehly/htmx-spring-workshop/assets/787481/8649c13f-9456-4c81-bba7-e5d7e5688116)

Code completion suggests to use `@template.UserRow` (with upper case **U**):

![image](https://github.com/tschuehly/htmx-spring-workshop/assets/787481/ae207810-1df6-4c08-8db3-c41b26f5c720)

I can confirm that the lower case variant does not work at runtime, while the upper case works fine.

So, I guess those lines in the docs should be changed:

https://github.com/tschuehly/htmx-spring-workshop/blob/93d6d556fe76a7e647c7d5762f681deadef21247/docs/lab-1-server-side-rendering-with-spring-boot-and-jte.md?plain=1#L84

https://github.com/tschuehly/htmx-spring-workshop/blob/93d6d556fe76a7e647c7d5762f681deadef21247/docs/lab-1-server-side-rendering-with-spring-boot-and-jte.md?plain=1#L137

(Unless it is part of the exercise to find out about this error, then feel free to close this issue. ;-))

**Comment by tschuehly** [comment]
Very weird, it works on branch lab-1 for me. But I will update it anyway

**Comment by tschuehly** [comment]
@Riggs333 
Could you try to checkout this tag and see if the error persists on your side? 
`git checkout tags/lab-1-checkpoint-1 -b current_lab`

**Comment by Riggs333** [comment]
Same error with tag `lab-1-checkpoint-1` and also with branch `lab-1`. 🤔 

I'm using:
- IntelliJ IDEA 2024.1.1 (Ultimate Edition), Build #IU-241.15989.150, built on April 29, 2024
- jte plugin version 2.1.2

**Comment by tschuehly** [comment]
Thanks for the issue!
